
[build]
rustflags = [
    "-C", "opt-level=3",
    "-C", "codegen-units=1",
    "-C", "panic=unwind",         # Good for diagnostics
    "-C", "overflow-checks=on",   # Good for safety
    "-C", "target-cpu=native"     # Optimize for your specific CPU
]
